/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

interface LinkProps {
  href: string;
  text: string;
}

export const NavLink = component$((props: LinkProps) => {
  return (
    <a
      href={props.href}
      class="no-underline opacity-90 cursor-pointer pointer-events-auto text-neutral-50 max-md:font-light"
    >
      {props.text}
    </a>
  );
});

export const Header = component$(() => {
  const navLinks = [
    { href: "/assist", text: "Assist" },
    { href: "/boost", text: "Boost" },
    { href: "/dev", text: "Dev" },
    { href: "/immerse", text: "Immerse" },
    { href: "/web", text: "Web" },
  ];

  return (
    <header class="flex gap-8 justify-center items-center py-5 w-full bg-black bg-opacity-90 max-md:flex max-md:mx-auto max-sm:hidden">
      <img
        loading="lazy"
        alt="Logo"
        src="https://cdn.builder.io/api/v1/image/assets%2F5d086b2108f645f2aa78ff97e6eb22cb%2Fa71aed067f64450fbd955d3660151f5f"
        class="object-contain opacity-90 aspect-square w-[23px]"
      />
      <nav class="flex gap-x-5 gap-y-5 gap-8">
        {navLinks.map((link) => (
          <NavLink key={link.href} href={link.href} text={link.text} />
        ))}
      </nav>
    </header>
  );
});