/**
 * This code was generated by Builder.io.
 */
import { component$, useStylesScoped$ } from "@builder.io/qwik"; 

interface LinkProps {
  href: string;
  text: string;
  className?: string;
}

const Link = component$(({ href, text, className }: LinkProps) => (
  <a href={href} class={className} role="link" tabindex="0">
    {text}
  </a>
));

export const MyComponent = component$(() => {
  useStylesScoped$(STYLES);

  const links = [
    { href: "/assist", text: "Assist", className: "nav-link" },
    { href: "/boost", text: "Boost", className: "nav-link" },
    { href: "/dev", text: "Dev", className: "nav-link" },
    { href: "/immerse", text: "Immerse", className: "nav-link" },
    { href: "/web", text: "Web", className: "nav-link" },
  ];

  return (
    <section class="nav-section">
      <img loading="lazy" alt="" src="https://cdn.builder.io/api/v1/image/assets%2F5d086b2108f645f2aa78ff97e6eb22cb%2Fa71aed067f64450fbd955d3660151f5f" class="nav-logo" />
      <nav class="nav">
        {links.map(link => (
          <Link href={link.href} text={link.text} className={link.className} />
        ))}
      </nav>
    </section>
  );
});

export const STYLES = `
.nav-section {
  align-items: center;
  background-color: rgba(0, 0, 0, 0.9);
  display: flex;
  justify-content: center;
  width: 100%;
  gap: 30px;
  padding: 20px 0;
}
@media (max-width: 991px) {
  .nav-section { 
    display: flex;
    margin: 0 auto;
  }
}
@media (max-width: 640px) {
  .nav-section {
    display: none;
  }
}
.nav-logo {
  aspect-ratio: 1 / 1;
  object-fit: contain;
  object-position: center;
  width: 23px;
  opacity: 0.9;
}
.nav {
  column-gap: 20px;
  display: flex;
  gap: 30px;
  row-gap: 20px;
}
.nav-link {
  text-decoration: none;
  color: rgba(250, 250, 250, 1);
  opacity: 0.9;
  font-family: "ui-sans-serif", sans-serif;
  cursor: pointer;
}
@media (max-width: 991px) {
  .nav-link {
    font-family: "ui-sans-serif", sans-serif;
    font-weight: 300;
  }
}
`;